>>> Personal_Information.objects.filter(first_name='Ami').values()
[{'last_name': u'Mehta', 'sex': u'Female', 'chart_no': 1L, 'account_status': u'Current', 'ethnicity':
D', 'city': u'Los Angeles', 'first_name': u'Ami', 'written_pref': u'Post', 'middle_name': u'b', 'zip':
90007', 'call_pref': u'Home', 'state': u'CA', 'home_phone': u'323-363-0858', 'email': u'', 'account_ty
: u'OF', 'emp_status': u'Full-Time Student', 'ssn': u'123-45-6789', 'address': u'720 W', 'sign': u'Yes
'language': u'en', 'dob': datetime.date(1991, 11, 21), 'country': u'US', 'date_registered': datetime.d
(2015, 10, 8), 'race': u'PD', 'cell_phone': u''}]
>>> Personal_Information.objects.filter(first_name='Ami')[0]
<Personal_Information: Ami Mehta>
>>> Personal_Information.objects.filter(first_name='Ami')[0].values()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
AttributeError: 'Personal_Information' object has no attribute 'values'
>>> Personal_Information.objects.filter(first_name='Ami')[0].all()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
AttributeError: 'Personal_Information' object has no attribute 'all'
>>> Personal_Information.objects.filter(first_name='Ami')[0].country
Country(code=u'US')
>>> Personal_Information.objects.filter(first_name='Ami')[0].country()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
TypeError: 'Country' object is not callable
>>> Personal_Information.objects.filter(first_name='Ami')[0].country
Country(code=u'US')
>>> Personal_Information.history.filter(history_user_id=2)[0].history_object.county
Traceback (most recent call last):
  File "<console>", line 1, in <module>
AttributeError: 'Personal_Information' object has no attribute 'county'
>>> Personal_Information.history.filter(history_user_id=2)[0].history_object.country
Country(code=u'US')
>>> Personal_Information.history.filter(history_user_id=2)[0].history_object.middle_name
u'JD'
>>> Personal_Information.history.filter(history_user_id=2)[0]
<HistoricalPersonal_Information: John Doe as of 2016-03-08 20:12:30.288000+00:00>
>>> Personal_Information.history.filter(history_user_id=2)[0].values()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
AttributeError: 'HistoricalPersonal_Information' object has no attribute 'values'